### PR TITLE
Update ExportTest.php

### PR DESCRIPTION
**Pull request by ralfbecker**
Test for 0 duration

### CODE REVIEW

**Comment by yunosh** [comment]
Oops, what happened here? Your editor messing up linebreaks? Please note that there are some CRLF linebreaks in the embedded iCalendar data.

**Comment by ralfbecker** [comment]
Hmm, I just pasted it into GitHubs editor. It's basically just one more method at end of the class:

     public function testDuration0()
    {
		$ical = new Horde_Icalendar;
		$vevent = Horde_Icalendar::newComponent('VEVENT', $ical);
		$vevent->setAttribute('SUMMARY', 'Testevent');
		$vevent->setAttribute('UID', 'XXX');
		$vevent->setAttribute('DTSTART', new DateTime('20150701T120000Z'));
		$vevent->setAttribute('DTSTAMP', new DateTime('20150701T120000Z'));
		$vevent->setAttribute('DURATION', 0);
		$ical->addComponent($vevent);
		$valarm = Horde_Icalendar::newComponent('VALARM', $vevent);
		$valarm->setAttribute('TRIGGER', 0, array(
			'VALUE' => 'DURATION',
			'RELATED' => 'START',
		));
		$valarm->setAttribute('DESCRIPTION', 'Alarm at event-start');
		$vevent->addComponent($valarm);
		$this->assertEquals(
			'BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//The Horde Project//Horde iCalendar Library//EN
BEGIN:VEVENT
SUMMARY:Testevent
UID:XXX
DTSTART:20150701T120000Z
DTSTAMP:20150701T120000Z
DURATION:PT0S
BEGIN:VALARM
TRIGGER;VALUE=DURATION;RELATED=START:PT0S
DESCRIPTION:Alarm at event-start
END:VALARM
END:VEVENT
END:VCALENDAR
',
            $ical->exportVCalendar()
        );
	}

Ralf

**Comment by yunosh** [comment]
I have split out the fixtures into separate files so that shouldn't be an issue anymore.

**Comment by ralfbecker** [comment]
Do you take care of merging it, or should I do something?

Ralf

**Comment by yunosh** [comment]
Please update your test addition to use a fixture like the other unit tests.

**Comment by ralfbecker** [comment]
Included in new pull request #141

**Pull request closed without merging**
