### PR TITLE
Provide sane default arguments

### PR DESCRIPTION
**Pull request by thomasjfox**
Default arguments have to be at the end of the argument list.
There's no way to skip parameters as in python.

Please have a careful look if the change
in luxor is correct or drop it otherwise.

### CODE REVIEW

**Comment by thomasjfox** [comment]
More default argument fun, but let's fix them in a separate step.

We could also argue that the default arguments in the middle
of a function definition give the developer a hint what a possible value could be.
In that case I can just exclude them from the CodeSniffer check.
Though that should rather be part of the docstring, no?

FILE: horde/horde/lib/Block/Sunrise.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 80 | ERROR | Arguments with default values must be at the end of the
    |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
----------------------------------------------------------------------

FILE: horde/framework/Core/lib/Horde/Core/Block/Layout/View.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 39 | ERROR | Arguments with default values must be at the end of the
    |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
----------------------------------------------------------------------

FILE: horde/framework/Dav/lib/Horde/Dav/Collection.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 79 | ERROR | Arguments with default values must be at the end of the
    |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
----------------------------------------------------------------------

FILE: horde/framework/Argv/test/Horde/Argv/TestCase.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 71 | ERROR | Arguments with default values must be at the end of the
    |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
----------------------------------------------------------------------

FILE: horde/framework/Pdf/lib/Horde/Pdf/Writer.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 1040 | ERROR | Arguments with default values must be at the end of the
      |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
 1098 | ERROR | Arguments with default values must be at the end of the
      |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
 1154 | ERROR | Arguments with default values must be at the end of the
      |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
----------------------------------------------------------------------

FILE: horde/framework/Imap_Client/lib/Horde/Imap/Client/Exception/ServerResponse.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 55 | ERROR | Arguments with default values must be at the end of the
    |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
----------------------------------------------------------------------

FILE: horde/framework/Rpc/lib/Horde/Rpc/Soap.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 131 | ERROR | Arguments with default values must be at the end of the
     |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
----------------------------------------------------------------------

**Comment by mrubinsk** [comment]
Quoting Thomas Jarosch <notifications@github.com>:

> More default argument fun, but let's fix them in a separate step.
>
> We could also argue that the default arguments in the middle
> of a function definition give the developer a hint what a possible  
> value could be.
> In that case I can just exclude them from the CodeSniffer check.

No, keep the check in. We should definitely not have arguments with no  
defaults after arguments that do.


> Though that should rather be part of the docstring, no?
>
> FILE: horde/horde/lib/Block/Sunrise.php
> ----------------------------------------------------------------------
> FOUND 1 ERROR AFFECTING 1 LINE
> ----------------------------------------------------------------------
>  80 | ERROR | Arguments with default values must be at the end of the
>     |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
> ----------------------------------------------------------------------
>
> FILE: horde/framework/Core/lib/Horde/Core/Block/Layout/View.php
> ----------------------------------------------------------------------
> FOUND 1 ERROR AFFECTING 1 LINE
> ----------------------------------------------------------------------
>  39 | ERROR | Arguments with default values must be at the end of the
>     |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
> ----------------------------------------------------------------------
>
> FILE: horde/framework/Dav/lib/Horde/Dav/Collection.php
> ----------------------------------------------------------------------
> FOUND 1 ERROR AFFECTING 1 LINE
> ----------------------------------------------------------------------
>  79 | ERROR | Arguments with default values must be at the end of the
>     |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
> ----------------------------------------------------------------------
>
> FILE: horde/framework/Argv/test/Horde/Argv/TestCase.php
> ----------------------------------------------------------------------
> FOUND 1 ERROR AFFECTING 1 LINE
> ----------------------------------------------------------------------
>  71 | ERROR | Arguments with default values must be at the end of the
>     |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
> ----------------------------------------------------------------------
>
> FILE: horde/framework/Pdf/lib/Horde/Pdf/Writer.php
> ----------------------------------------------------------------------
> FOUND 3 ERRORS AFFECTING 3 LINES
> ----------------------------------------------------------------------
>  1040 | ERROR | Arguments with default values must be at the end of the
>       |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
>  1098 | ERROR | Arguments with default values must be at the end of the
>       |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
>  1154 | ERROR | Arguments with default values must be at the end of the
>       |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
> ----------------------------------------------------------------------
>
> FILE:  
> horde/framework/Imap_Client/lib/Horde/Imap/Client/Exception/ServerResponse.php
> ----------------------------------------------------------------------
> FOUND 1 ERROR AFFECTING 1 LINE
> ----------------------------------------------------------------------
>  55 | ERROR | Arguments with default values must be at the end of the
>     |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
> ----------------------------------------------------------------------
>
> FILE: horde/framework/Rpc/lib/Horde/Rpc/Soap.php
> ----------------------------------------------------------------------
> FOUND 1 ERROR AFFECTING 1 LINE
> ----------------------------------------------------------------------
>  131 | ERROR | Arguments with default values must be at the end of the
>      |       | argument list (PEAR.Functions.ValidDefaultValue.NotAtEnd)
> ----------------------------------------------------------------------
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/horde/horde/pull/150#issuecomment-129605591



-- 
mike
The Horde Project
http://www.horde.org
https://www.facebook.com/hordeproject
https://www.twitter.com/hordeproject

**Comment by slusarz** [comment]
...except this is acceptable in certain cases (or at least it used to be in PHP).

Think of overriding a parent function with an optional argument, and the child function adds a mandatory argument.  This additional (mandatory) argument necessarily needs to occur at the end.

**Comment by mrubinsk** [comment]
Quoting Michael M Slusarz <notifications@github.com>:

> ...except this is acceptable in certain cases (or at least it used  
> to be in PHP).
>
> Think of overriding a parent function with an optional argument, and  
> the child function adds a mandatory argument.  This additional  
> (mandatory) argument necessarily needs to occur at the end.

Agreed, but shouldn't the overridden function then remove the default  
value of the parent method since it is now no longer optional? This  
will still match the signature, since overridden classes are allowed  
to contain less optional arguments then the parent.

-- 
mike
The Horde Project
http://www.horde.org
https://www.facebook.com/hordeproject
https://www.twitter.com/hordeproject

**Comment by slusarz** [comment]
On 8/10/2015 4:16 PM, Michael J Rubinsky wrote:
>
> This
> will still match the signature, since overridden classes are allowed
> to contain less optional arguments then the parent.

This is exactly what I thought PHP doesn't allow.  At least in some 
versions (i.e., removing default arguments causes the incorrect function 
signature error to be thrown).

But admittedly I don't if I am remembering correctly, and unfortunately 
don't have the time at the moment to research this statement.

**Comment by mrubinsk** [comment]
I fixed most of the items on the list above. I didn't touch the following:

The Dav:: stuff. Jan wrote that fairly recently, and has a fairly large inheritance tree so I'm reluctant to make changes to that give the concerns Michael S. has raised.

The Horde_Imap_Client stuff: I'll let Michael S. touch that if he feels it's necessary.

**Comment by thomasjfox** [comment]
Cool!

I surfed the net a bit about overriding functions in PHP and if it's a valid (=stable) thing to add mandatory parameters for an existing function in a derived class. IMHO that really changes the signature of the method in an incompatible way and might break if a program just operates on the methos of the base class.

See also:
http://stackoverflow.com/questions/13423494/why-is-overriding-method-parameters-a-violation-of-strict-standards-in-php

As [mms] pointed out, more research is needed. Later on ;)

**Comment by mrubinsk** [comment]
Quoting Thomas Jarosch <notifications@github.com>:

> Cool!
>
> I surfed the net a bit about overriding functions in PHP and if it's  
> a valid (=stable) thing to add mandatory parameters for an existing  
> function in a derived class. IMHO that really changes the signature  
> of the method in an incompatible way and might break if a program  
> just operates on the methos of the base class.
>
> See also:
> http://stackoverflow.com/questions/13423494/why-is-overriding-method-parameters-a-violation-of-strict-standards-in-php
>
> As [mms] pointed out, more research is needed. Later on ;)

I agree. Only optional arguments should ever be added to a child  
class' method signatures when that method is @Overide. This is why I  
only changed the signatures on the classes that did not violate this.  
Well, except for the SOAP class, but that method signature is already  
completely different as it is...

-- 
mike
The Horde Project
http://www.horde.org
https://www.facebook.com/hordeproject
https://www.twitter.com/hordeproject

**Pull request closed without merging**
