### PR TITLE
Fix duplicated Horde_Service_Vimeo_Simple class name

### PR DESCRIPTION
**Pull request by thomasjfox**
Cherry pick time :)

### CODE REVIEW

**Comment by thomasjfox** [comment]
The failed travis test is some PGP stuff using PHP 5.4 environment.

**Comment by mrubinsk** [comment]
Quoting Thomas Jarosch <notifications@github.com>:

> The failed travis test is some PGP stuff using PHP 5.4 environment.


Yeah, this is a common occurrence. Both Jan and I have spent a bit of  
time trying to get that test to pass on Travis. :/

-- 
mike
The Horde Project
http://www.horde.org
https://www.facebook.com/hordeproject
https://www.twitter.com/hordeproject

**Comment by thomasjfox** [comment]
Is it always the 'Horde_Pgp_Backend_OpenpgpTest::testEncryptSymmetric' test failing or do random PGP tests fail?

**Comment by mrubinsk** [comment]
Quoting Thomas Jarosch <notifications@github.com>:

> Is it always the  
> 'Horde_Pgp_Backend_OpenpgpTest::testEncryptSymmetric' test failing  
> or do random PGP tests fail?


Not random, but also the   
Horde_Pgp_KeyserverTest::testKeyserverRetrieveByEmail fails  
occasionally as well.


-- 
mike
The Horde Project
http://www.horde.org
https://www.facebook.com/hordeproject
https://www.twitter.com/hordeproject

**Pull request closed without merging**
