### PR TITLE
Added Horde_Memcached driver

### PR DESCRIPTION
**Pull request by acmpires**
Memcached driver.

### CODE REVIEW

**Comment by ralflang** [comment]
Hi Carlos, this is really appreciated. I looked a little at the code but currently lack time to com

**Comment by ralflang** [comment]
pletely review and merge - maybe some other core member is faster than I am.

**Comment by acmpires** [comment]
We already have it on production and it's working fine. The big keys logic changes a bit.

**Comment by yunosh** [comment]
Is there any reason why you didn't fold this into Horde_Memcache as an alternative driver?

**Comment by acmpires** [comment]
Just made a test on PHP7 and some changes are needed for PHP7, the Memcached::getMulti API changed.

**Comment by acmpires** [comment]
No reason, just started with a copy of Horde_Memcache driver.

**Comment by yunosh** [comment]
Can you please merge the changes into Horde_Memcache, so we can use both extensions interchangeably?

**Comment by yunosh** [comment]
memcached support has been added to Horde_Memcache in version 2.1.0

**Pull request closed without merging**
