### PR TITLE
add ThreadTopic class

### PR DESCRIPTION
**Pull request by leithoff**
as usage of Thread-Topic increases and it may hold utf-8 special handling is suggested

### CODE REVIEW

**Comment by slusarz** [comment]
Why would thread-topic usage "increase"?  It's a proprietary header, and Microsoft's e-mail share is falling.

What does thread-topic provide that References/In-Reply-To (RFC 5322) & IMAP thread sorting (RFC 5256) doesn't?  Especially since thread-topic and thread-index have been deprecated by Microsoft itself in favor of the latter technologies.

**Comment by leithoff** [comment]
The alternative would be ignoring it.
Its not how often it is used its that it is, and that if used and has utf-8 
characters some servers complain and do not allow it at all on sending, 
others regard such messages as spam on zhe incomming side
My reasoning is simple:
Its used. And since it is, i think "we" should handle it "correctly".
Or we shoul take measures that it is not handeled at all.

If you think we should not care. Its fine by me.

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 4. März 2015 06:56:07 schrieb Michael M Slusarz <notifications@github.com>:

**Comment by slusarz** [comment]
Thread-Topic is **not** used by anything outside of Exchange (and it's not even used in Exchange anymore).  

And I don't understand how adding a Horde_Mime_Headers class to handle this particular header has anything to do with sending or spam.  Horde/IMP doesn't add this header anywhere, and adding a new header object doesn't change that - you actually have to add the header to an outgoing message, which this patch (nor the one in #124) doesn't do.

There's a bunch of headers Horde doesn't handle, and that's the whole design of e-mail headers -- you can ignore the ones that don't add meaningful information 

Finally, I'm confused why you mention aqua mail.  They are looking to add threading support in exactly the way I described above (References/In-Reply-To; see http://www.aqua-mail.com/forum/index.php?topic=2495.0).  Meaning the exact same threading support which IMP has had for 15 years.

**Comment by leithoff** [comment]
sorry aquamail is yust the mailer on this smartphone. Has nothing to do 
with the topic from my point of view

You are correct.
I was explizitly adding the particular header. As customer requested it.
While doing this using addHeader i was not able to do that without ending 
up with getting the utf-8 stuff into the header.
Even sending it in encoded was resolving it to the unencoded utf-8 when 
sending out. Adding the headerhandling class was the only way.

I am quite sure that microsoft is acting as you state that. Only customers 
have a funny habbit of not using the latest stuff and requesting the error 
free software at the same time ;-)

Michael dont waste your time on that topic. It is not worth a discussion of 
principles
Its "your" software. I do understand your reasoning and accept it easily 
when you say no: "This piece of code should not be part of the software."
Thanks for your time and effort and explanations.

Best regards
Klaus

Gesendet mit AquaMail für Android
http://www.aqua-mail.com

**Pull request closed without merging**
