### PR TITLE
duration without time ("P") is NOT valid, append 0 seconds ("T0S")

### PR DESCRIPTION
**Pull request by ralfbecker**
Fix plus test in one pull request.

Hope that's it.

Ralf

### CODE REVIEW

**Comment by yunosh** [comment]
Besides that your test fails, yes :-)
See https://travis-ci.org/horde/horde/jobs/68488018#L829

**Comment by ralfbecker** [comment]
Hi Jan,
no idea why this keeps failing: https://travis-ci.org/horde/horde/jobs/68540242#L834
The fixture is exactly like the returned result. I wonder if this is due the fact that it says expected but shows nothing ...
Can you have a quick look please :-)
Ralf

**Comment by yunosh** [comment]
The line endings were incorrect. iCalendar data must have CRLF line endings. Thanks for your patience!

**Comment by ralfbecker** [comment]
Thanks :-)

**Pull request merged**
