### PR TITLE
Fix namespace issues in Horde\ManageSieve causing PHP Fatal errors

### PR DESCRIPTION
**Pull request by ralfbecker**

### CODE REVIEW

**Comment by ralfbecker** [comment]
Can't see that any of the build failures have something to do with code changed in my pull-request.

Ralf

**Comment by yunosh** [comment]
Are you going to update the PR? Thanks.

**Comment by ralfbecker** [comment]
Yeap, I was in a meeting, doing it now.

Ralf

**Comment by ralfbecker** [comment]
Done

**Comment by yunosh** [comment]
Testing this further, remove the "use" lines didn't work either because now the base exception class cannot be found. What we actually need is along the lines:
```PHP
namespace Horde\ManageSieve\Exception;
use Horde\ManageSieve;
class NotDisconnected extends ManageSieve\Exception
```

**Comment by ralfbecker** [comment]
Hi Jan, 

basic functionality including euser for Cyrus is working now. So from my point of view, you can commit that pull request now and release a new package with it.

We had some special code for certain mailservers around sasl and using plain instead of login for an euser, which I need to get Klaus to test against these servers. These tests might take a while and we can open a new pull request / discussion, if we still have problems with them.

Ralf

**Comment by yunosh** [comment]
Thanks for all the testing and improvements.

**Comment by ralfbecker** [comment]
Thanks Jan :)

I just noticed 1.0.1 release still has date 2015-11-15 from 1.0.0.

Are commited releases automatically build on pear.horde.org, or how does that work?

Ralf

**Comment by yunosh** [comment]
No, releases are built semi-automatically but manually triggered. Dates are updated automatically once the 1.0.1 release is finally rolling.

**Pull request merged**
