### PR TITLE
Kolab_Storage: Improve cleanup of duplicated objects

### PR DESCRIPTION
**Pull request by thomasjfox**
In the real world it can happen that two messages
with the some Kolab XML uid appear in an IMAP folder.

This could be due to user error or a Kolab client
that first stores the new version of an object
and then deletes the old message.

The current code removes the Kolab object completely
from the cache when an old duplicate message gets expunged.

Fix it by only removing the object from the cache
if the latest version of the object gets deleted.

The fix is not perfect as it does not cover the case
when the latest version (=highest IMAP uid) gets removed
and the old one remains. That case is more complicated
as we need to update the Horde_History, too.

Pull request note: The change is quite minimal if you ignore the changes in indent caused by the new if statement.

### CODE REVIEW

**Comment by mrubinsk** [comment]
In what case would the latest version (highest UID) be deleted, but the older version remain? Wouldn't deleting the most recent version of the object essentially indicate the object was explicitly removed? I.e., we could also remove the other instance of it as well? Or am I misunderstanding Kolab again?

**Comment by thomasjfox** [comment]
On Friday, 18. September 2015 06:54:15 Michael J Rubinsky wrote:
> In what case would the latest version (highest UID) be deleted, but the
> older version remain? Wouldn't deleting the most recent version of the
> object essentially indicate the object was explicitly removed? I.e., we
> could also remove the other instance of it as well? Or am I
> misunderstanding Kolab again?

let's assume the user notices there are f.e. three versions of
the same object stored on the server. He deletes two messages.

If those two messages are the old ones, all is fine.

If one message was the one with the highest IMAP uid, the "bid" in the 
Horde_History table will be incorrect. Not that it's used for any useful 
checks, but it's still incorrect.

I would only assume a object was finally deleted when all versions are gone. 
It can happen that when two or more clients work on the same object that 
duplicates get created. Think about a client that's working in a 
"disconnected IMAP" mode because you are traveling.

Also a client could be implemented in a dumb way to always produce 
duplicates by storing the new message first and then delete the old one.
The current code would remove that object.

The decision if an object is unwanted or not should always be left to the 
user. Kolab_Storage already makes note of the duplicates internally,
but that information is not used in the UI.

Does that clarify it a bit?

Thomas

**Comment by mrubinsk** [comment]
Indeed it does. I wasn't thinking of the user interacting directly with the IMAP store to remove messages. I was also thinking of the duplicates as "ghosts" that were no longer valid and that would not appear in the UI. Thanks.

**Comment by thomasjfox** [comment]
currently duplicates don't appear in horde.
We just take the most current version.

The user might interact directly with the IMAP store,
but that's rather unusual. Conflict management might be
a built-in feature of a non-horde client though.

There's even a crazy state diagram here on conflict resolution:
https://wiki.kolab.org/Conflict_Resolution

While I think that's a bit "too much" for my taste,
let's just make sure we don't trash any data for now.
It's better to have duplicates than to have no data at all :)

Have a nice weekend!

Am Freitag, 18. September 2015, 09:57:37 schrieb Michael J Rubinsky:

**Comment by mrubinsk** [comment]
Cherry picked, thanks.

**Pull request closed without merging**
