### PR TITLE
More reliable way to get list of visible indexes and table

### PR DESCRIPTION
**Pull request by sathieu**
without dealing with search_path Got rid of bugged getSchemaSearchPath()

### CODE REVIEW

**Comment by sathieu** [comment]
This patch comes from https://bugs.debian.org/810858

**Comment by yunosh** [comment]
Well, theoretically we still support version 7. But since this is dead for five years now, and even version is EOL'ed, it's probably time to move on. I'll get a quick survey first though.

**Comment by Ivan-SB** [comment]
To help you in the survey:

Postgres 7.0 is older than Windows XP.
Postgres 8.0 is nearly as old as PHP 5.0 (more than 10 years).

RHEL 4 was shipping with 7.4 and its extended lifecycle support will end next year. But it is already out of Production 3 phase by 3 years.
It was shipping with PHP 4.3 though, can horde run on PHP 4.3?

RHEL 5 was already shipping with pg 8.1 (and PHP 5.1)

**Comment by yunosh** [comment]
Merged, thanks

**Comment by sathieu** [comment]
@yunosh, do you plan to release it in Horde_Db 2.3.1?

**Comment by yunosh** [comment]
No, because it has already been released in 2.3.1.

**Comment by sathieu** [comment]
OK. Sorry for the noise :no_bell:

**Comment by Ivan-SB** [comment]
Thanks to everybody for making it so fast.
In too many PHP applications postgresql is considered a stepchild.
I'm going to test Debian packages as soon as they reach one of the mirror I'm used to use.

**Pull request closed without merging**
